export const jnvSchools = {
  "Andaman and Nicobar Islands": [
    "JNV Diglipur",
    "JNV Car Nicobar",
    "JNV Nancowry",
    "JNV Campbell Bay",
  ],
  "Andhra Pradesh": [
    "JNV Chittoor",
    "JNV Kadapa",
    "JNV Kurnool",
    "JNV Nellore",
    "JNV Prakasam",
    "JNV Srikakulam",
    "JNV Visakhapatnam",
    "JNV Vizianagaram",
    "JNV West Godavari",
    "JNV East Godavari",
    "JNV Guntur",
    "JNV Krishna",
    "JNV Anantapur",
  ],
  "Arunachal Pradesh": [
    "JNV Tawang",
    "JNV West Kameng",
    "JNV East Kameng",
    "JNV Papum Pare",
    "JNV Kurung Kumey",
    "JNV Kra Daadi",
    "JNV Lower Subansiri",
    "JNV Upper Subansiri",
    "JNV West Siang",
    "JNV East Siang",
    "JNV Upper Siang",
    "JNV Dibang Valley",
    "JNV Lower Dibang Valley",
    "JNV Lohit",
    "JNV Anjaw",
    "JNV Changlang",
    "JNV Tirap",
    "JNV Longding",
  ],
  Assam: [
    "JNV Baksa",
    "JNV Barpeta",
    "JNV Biswanath",
    "JNV Bongaigaon",
    "JNV Cachar",
    "JNV Charaideo",
    "JNV Chirang",
    "JNV Darrang",
    "JNV Dhemaji",
    "JNV Dhubri",
    "JNV Dibrugarh",
    "JNV Goalpara",
    "JNV Golaghat",
    "JNV Hailakandi",
    "JNV Hojai",
    "JNV Jorhat",
    "JNV Kamrup",
    "JNV Kamrup Metropolitan",
    "JNV Karbi Anglong",
    "JNV Karimganj",
    "JNV Kokrajhar",
    "JNV Lakhimpur",
    "JNV Majuli",
    "JNV Morigaon",
    "JNV Nagaon",
    "JNV Nalbari",
    "JNV Sivasagar",
    "JNV Sonitpur",
    "JNV South Salmara-Mankachar",
    "JNV Tinsukia",
    "JNV Udalguri",
    "JNV West Karbi Anglong",
  ],
  Bihar: [
    "JNV Araria",
    "JNV Arwal",
    "JNV Aurangabad",
    "JNV Banka",
    "JNV Begusarai",
    "JNV Bhagalpur",
    "JNV Bhojpur",
    "JNV Buxar",
    "JNV Darbhanga",
    "JNV East Champaran",
    "JNV Gaya",
    "JNV Gopalganj",
    "JNV Jamui",
    "JNV Jehanabad",
    "JNV Kaimur",
    "JNV Katihar",
    "JNV Khagaria",
    "JNV Kishanganj",
    "JNV Lakhisarai",
    "JNV Madhepura",
    "JNV Madhubani",
    "JNV Munger",
    "JNV Muzaffarpur",
    "JNV Nalanda",
    "JNV Nawada",
    "JNV Patna",
    "JNV Purnia",
    "JNV Rohtas",
    "JNV Saharsa",
    "JNV Samastipur",
    "JNV Saran",
    "JNV Sheikhpura",
    "JNV Sheohar",
    "JNV Sitamarhi",
    "JNV Siwan",
    "JNV Supaul",
    "JNV Vaishali",
    "JNV West Champaran",
  ],
  "Chandigarh (UT)": ["JNV Chandigarh"],
  Chhattisgarh: [
    "JNV Balod",
    "JNV Baloda Bazar",
    "JNV Balrampur",
    "JNV Bemetara",
    "JNV Bijapur",
    "JNV Dantewada",
    "JNV Dhamtari",
    "JNV Durg",
    "JNV Gariyaband",
    "JNV Janjgir Champa",
    "JNV Jashpur",
    "JNV Kabirdham",
    "JNV Kanker",
    "JNV Kondagaon",
    "JNV Korba",
    "JNV Mahasamund",
    "JNV Mungeli",
    "JNV Narayanpur",
    "JNV Raigarh",
    "JNV Raipur",
    "JNV Rajnandgaon",
    "JNV Sukma I",
    "JNV Sukma II",
    "JNV Surajpur",
    "JNV Surguja",
    "JNV Balodabazar",
    "JNV Korea",
  ],
  "Dadra and Nagar Haveli (UT)": ["JNV Dadra and Nagar Haveli"],
  "Daman and Diu (UT)": ["JNV Daman and Diu"],
  "Delhi (NCT)": ["JNV Dwarka", "JNV New Delhi", "JNV Rohini"],
  Goa: ["JNV Goa"],
  Gujarat: [
    "JNV Ahmedabad",
    "JNV Amreli",
    "JNV Anand",
    "JNV Aravalli",
    "JNV Banaskantha",
    "JNV Bharuch",
    "JNV Bhavnagar",
    "JNV Botad",
    "JNV Dahod I",
    "JNV Dahod II",
    "JNV Dang",
    "JNV Gandhi Nagar",
    "JNV Gir Somnath",
    "JNV Jamnagar",
    "JNV Junagadh",
    "JNV Kheda",
    "JNV Kutch",
    "JNV Mahisagar",
    "JNV Mehsana",
    "JNV Narmada",
    "JNV Navsari",
    "JNV Panchmahal",
    "JNV Patan",
    "JNV Porbandar",
    "JNV Rajkot",
    "JNV Sabarkantha",
    "JNV Surendranagar",
    "JNV Tapi",
    "JNV Vadodara",
    "JNV Valsad",
    "JNV Devbhumi Dwarka",
  ],
  Haryana: [
    "JNV Bhiwani",
    "JNV Faridabad",
    "JNV Fatehabad",
    "JNV Hisar",
    "JNV Jhajjar",
    "JNV Jind",
    "JNV Kaithal",
    "JNV Karnal",
    "JNV Kurukshetra",
    "JNV Mahendragarh",
    "JNV Mewat",
    "JNV Palwal",
    "JNV Panipat",
    "JNV Rewari",
    "JNV Rohtak",
    "JNV Sirsa",
    "JNV Sonipat",
    "JNV Yamunanagar",
  ],
  "Himachal Pradesh": [
    "JNV Bilaspur",
    "JNV Chamba",
    "JNV Hamirpur",
    "JNV Kangra",
    "JNV Kinnaur",
    "JNV Kullu",
    "JNV Mandi",
    "JNV Shimla",
    "JNV Sirmaur",
    "JNV Solan",
    "JNV Una",
  ],
  "Jammu and Kashmir UT": [
    "JNV Anantnag",
    "JNV Bandipora",
    "JNV Baramulla",
    "JNV Budgam",
    "JNV Doda",
    "JNV Ganderbal",
    "JNV Jammu-I",
    "JNV Jammu-II",
    "JNV Kathua",
    "JNV Kishtwar",
    "JNV Kulgam",
    "JNV Kupwara",
    "JNV Poonch",
    "JNV Pulwama",
    "JNV Rajouri",
    "JNV Ramban",
    "JNV Reasi",
    "JNV Samba",
    "JNV Shopian",
    "JNV Srinagar",
    "JNV Udhampur",
  ],
  Jharkhand: [
    "JNV Bokaro",
    "JNV Chatra",
    "JNV Deoghar",
    "JNV Dhanbad",
    "JNV Dumka",
    "JNV East Singhbhum",
    "JNV Garhwa",
    "JNV Giridih",
    "JNV Godda",
    "JNV Gumla",
    "JNV Hazaribagh",
    "JNV Jamtara",
    "JNV Khunti",
    "JNV Koderma",
    "JNV Latehar",
    "JNV Lohardaga",
    "JNV Pakur",
    "JNV Palamu",
    "JNV Ramgarh",
    "JNV Ranchi",
    "JNV Sahebganj",
    "JNV Seraikela Kharsawan",
    "JNV Simdega",
    "JNV West Singhbhum",
  ],
  Karnataka: [
    "JNV Bagalkot",
    "JNV Bangalore Rural",
    "JNV Bangalore Urban",
    "JNV Belgaum",
    "JNV Bellary",
    "JNV Bidar",
    "JNV Bijapur",
    "JNV Chamarajanagar",
    "JNV Chikballapur",
    "JNV Chikmagalur",
    "JNV Chitradurga",
    "JNV Dakshina Kannada",
    "JNV Davanagere",
    "JNV Dharwad",
    "JNV Gadag",
    "JNV Gulbarga",
    "JNV Hassan",
    "JNV Haveri",
    "JNV Kodagu",
    "JNV Kolar",
    "JNV Koppal",
    "JNV Mandya",
    "JNV Mysore",
    "JNV Raichur",
    "JNV Ramanagara",
    "JNV Shimoga",
    "JNV Tumkur",
    "JNV Udupi",
    "JNV Uttara Kannada",
    "JNV Vijayapura",
    "JNV Yadgir",
  ],
  Kerala: [
    "JNV Alappuzha",
    "JNV Ernakulam",
    "JNV Idukki",
    "JNV Kannur",
    "JNV Kasaragod",
    "JNV Kollam",
    "JNV Kottayam",
    "JNV Kozhikode",
    "JNV Malappuram",
    "JNV Palakkad",
    "JNV Pathanamthitta",
    "JNV Thiruvananthapuram",
    "JNV Thrissur",
    "JNV Wayanad",
  ],
  "Ladakh UT": ["JNV Kargil", "JNV Leh"],
  "Lakshadweep (UT)": ["JNV Kavaratti"],
  "Madhya Pradesh": [
    "JNV Agar Malwa",
    "JNV Alirajpur",
    "JNV Anuppur",
    "JNV Ashoknagar",
    "JNV Balaghat",
    "JNV Barwani",
    "JNV Betul",
    "JNV Bhind",
    "JNV Bhopal",
    "JNV Burhanpur",
    "JNV Chhatarpur",
    "JNV Chhindwara",
    "JNV Damoh",
    "JNV Datia",
    "JNV Dewas",
    "JNV Dhar",
    "JNV Dindori",
    "JNV Guna",
    "JNV Gwalior",
    "JNV Indore",
    "JNV Jabalpur",
    "JNV Jhabua I",
    "JNV Jhabua II",
    "JNV Katni",
    "JNV Khandwa",
    "JNV Khargone",
    "JNV Mandla",
    "JNV Mandsaur",
    "JNV Morena",
    "JNV Narsinghpur",
    "JNV Neemuch",
    "JNV Niwari",
    "JNV Panna",
    "JNV Raisen",
    "JNV Rajgarh",
    "JNV Ratlam",
    "JNV Ratlam II",
    "JNV Rewa",
    "JNV Sagar",
    "JNV Satna",
    "JNV Sehore",
    "JNV Seoni",
    "JNV Shahdol",
    "JNV Shajapur",
    "JNV Sheopur",
    "JNV Shivpuri",
    "JNV Sidhi",
    "JNV Singrauli",
    "JNV Tikamgarh",
    "JNV Ujjain",
    "JNV Vidisha",
  ],
  Maharashtra: [
    "JNV Amravati",
    "JNV Aurangabad",
    "JNV Beed",
    "JNV Chandrapur",
    "JNV Dhule",
    "JNV Gadchiroli",
    "JNV Gondia",
    "JNV Hingoli",
    "JNV Jalgaon",
    "JNV Kolhapur",
    "JNV Latur",
    "JNV Mumbai",
    "JNV Nagpur",
    "JNV Nanded",
    "JNV Nashik",
    "JNV Osmanabad",
    "JNV Palghar",
    "JNV Parbhani",
    "JNV Pune",
    "JNV Raigad",
    "JNV Ratnagiri",
    "JNV Satara",
    "JNV Sindhudurg",
    "JNV Solapur",
    "JNV Thane",
    "JNV Wardha",
    "JNV Washim",
    "JNV Yavatmal",
  ],
  Manipur: [
    "JNV Bishnupur",
    "JNV Chandel",
    "JNV Churachandpur",
    "JNV Imphal East",
    "JNV Imphal West",
    "JNV Senapati",
    "JNV Tamenglong",
    "JNV Thoubal",
  ],
  Meghalaya: [
    "JNV East Garo Hills",
    "JNV Ri-Bhoi",
    "JNV South Garo Hills",
    "JNV South West Garo Hills",
    "JNV West Garo Hills",
    "JNV West Khasi Hills",
  ],
  Mizoram: [
    "JNV Aizawl",
    "JNV Champhai",
    "JNV Kolashib",
    "JNV Lawngtlai",
    "JNV Lunglei",
    "JNV Mamit",
    "JNV Saiha",
    "JNV Serchhip",
  ],
  Nagaland: [
    "JNV Dimapur",
    "JNV Kiphire",
    "JNV Kohima",
    "JNV Longleng",
    "JNV Mon",
    "JNV Mokokchung",
    "JNV Phek",
    "JNV Tuensang",
    "JNV Wokha",
    "JNV Zunheboto",
  ],
  Odisha: [
    "JNV Angul",
    "JNV Balasore",
    "JNV Bargarh",
    "JNV Bhadrak",
    "JNV Boudh",
    "JNV Cuttack",
    "JNV Deogarh",
    "JNV Dhenkanal",
    "JNV Gajapati",
    "JNV Ganjam",
    "JNV Jagatsinghpur",
    "JNV Jajpur",
    "JNV Kendrapara",
    "JNV Keonjhar",
    "JNV Khordha",
    "JNV Koraput",
    "JNV Malkangiri",
    "JNV Nayagarh",
    "JNV Nuapada",
    "JNV Puri",
    "JNV Rayagada",
    "JNV Sambalpur",
    "JNV Sonepur",
    "JNV Sundargarh",
  ],
  "Puducherry (UT)": ["JNV Karaikal", "JNV Pondicherry"],
  Punjab: [
    "JNV Amritsar",
    "JNV Barnala",
    "JNV Bathinda",
    "JNV Faridkot",
    "JNV Fatehgarh Sahib",
    "JNV Gurdaspur",
    "JNV Hoshiarpur",
    "JNV Jalandhar",
    "JNV Kapurthala",
    "JNV Ludhiana",
    "JNV Mansa",
    "JNV Mohali",
    "JNV Pathankot",
    "JNV Patiala",
    "JNV Rupnagar",
    "JNV Sangrur",
  ],
  Rajasthan: [
    "JNV Ajmer",
    "JNV Alwar",
    "JNV Banswara",
    "JNV Baran",
    "JNV Barmer",
    "JNV Bharatpur",
    "JNV Bhilwara",
    "JNV Bikaner",
    "JNV Bundi",
    "JNV Chittorgarh",
    "JNV Dausa",
    "JNV Dhunkar",
    "JNV Ganganagar",
    "JNV Hanumangarh",
    "JNV Jaipur",
    "JNV Jaisalmer",
    "JNV Jalore",
    "JNV Jhunjhunu",
    "JNV Jodhpur",
    "JNV Karauli",
    "JNV Kota",
    "JNV Nagaur",
    "JNV Pali",
    "JNV Pratapgarh",
    "JNV Rajsamand",
    "JNV Sawai Madhopur",
    "JNV Sikar",
    "JNV Sirohi",
    "JNV Tonk",
    "JNV Udaipur",
  ],
  Sikkim: [
    "JNV East Sikkim",
    "JNV North Sikkim",
    "JNV South Sikkim",
    "JNV West Sikkim",
  ],
  "Tamil Nadu": [
    "JNV Ariyalur",
    "JNV Chennai",
    "JNV Coimbatore",
    "JNV Cuddalore",
    "JNV Dharmapuri",
    "JNV Dindigul",
    "JNV Erode",
    "JNV Kanchipuram",
    "JNV Kanyakumari",
    "JNV Karur",
    "JNV Krishnagiri",
    "JNV Madurai",
    "JNV Nagapattinam",
    "JNV Namakkal",
    "JNV Nilgiris",
    "JNV Perambalur",
    "JNV Pudukkottai",
    "JNV Ramanathapuram",
    "JNV Salem",
    "JNV Sivaganga",
    "JNV Thanjavur",
    "JNV Thiruvarur",
    "JNV Tiruchirappalli",
    "JNV Tirunelveli",
    "JNV Tirupattur",
    "JNV Tiruppur",
    "JNV Thoothukudi",
    "JNV Vellore",
    "JNV Villupuram",
  ],
  Telangana: [
    "JNV Adilabad",
    "JNV Hyderabad",
    "JNV Jagtial",
    "JNV Karimnagar",
    "JNV Khammam",
    "JNV Mahabubnagar",
    "JNV Medak",
    "JNV Nalgonda",
    "JNV Nizamabad",
    "JNV Rangareddy",
    "JNV Sangareddy",
    "JNV Siddipet",
    "JNV Vikarabad",
    "JNV Warangal",
  ],
  Tripura: [
    "JNV Dhalai",
    "JNV North Tripura",
    "JNV South Tripura",
    "JNV West Tripura",
  ],
  "Uttar Pradesh": [
    "JNV Agra",
    "JNV Aligarh",
    "JNV Allahabad",
    "JNV Ambedkar Nagar",
    "JNV Amroha",
    "JNV Auraiya",
    "JNV Azamgarh",
    "JNV Badayun",
    "JNV Bahraich",
    "JNV Ballia",
    "JNV Banda",
    "JNV Barabanki",
    "JNV Bareilly",
    "JNV Basti",
    "JNV Bhadohi",
    "JNV Bijnor",
    "JNV Budaun",
    "JNV Bulandshahr",
    "JNV Chandauli",
    "JNV Deoria",
    "JNV Etah",
    "JNV Etawah",
    "JNV Faizabad",
    "JNV Farrukhabad",
    "JNV Fatehpur",
    "JNV Firozabad",
    "JNV Gautam Buddh Nagar",
    "JNV Ghaziabad",
    "JNV Ghazipur",
    "JNV Gorakhpur",
    "JNV Hamirpur",
    "JNV Hardoi",
    "JNV Hathras",
    "JNV Jalaun",
    "JNV Jaunpur",
    "JNV Jhansi",
    "JNV Kanpur Dehat",
    "JNV Kanpur Nagar",
    "JNV Kannauj",
    "JNV Kasganj",
    "JNV Kaushambi",
    "JNV Kushinagar",
    "JNV Lalitpur",
    "JNV Lucknow",
    "JNV Mahoba",
    "JNV Mainpuri",
    "JNV Mathura",
    "JNV Meerut",
    "JNV Mirzapur",
    "JNV Moradabad",
    "JNV Muzaffarnagar",
    "JNV Pilibhit",
    "JNV Pratapgarh",
    "JNV Rae Bareli",
    "JNV Rampur",
    "JNV Saharanpur",
    "JNV Sant Kabir Nagar",
    "JNV Siddharthnagar",
    "JNV Shahjahanpur",
    "JNV Shamli",
    "JNV Shravasti",
    "JNV Sonbhadra",
    "JNV Sultanpur",
    "JNV Unnao",
    "JNV Varanasi",
  ],
  Uttarakhand: [
    "JNV Almora",
    "JNV Bageshwar",
    "JNV Chamoli",
    "JNV Dehradun",
    "JNV Haridwar",
    "JNV Nainital",
    "JNV Pauri Garhwal",
    "JNV Pithoragarh",
    "JNV Rudraprayag",
    "JNV Tehri Garhwal",
    "JNV Udham Singh Nagar",
    "JNV Uttarkashi",
  ],
  "West Bengal": [
    "JNV Alipurduar",
    "JNV Bankura",
    "JNV Birbhum",
    "JNV Cooch Behar",
    "JNV Darjeeling",
    "JNV Dakshin Dinajpur",
    "JNV Hooghly",
    "JNV Howrah",
    "JNV Jalpaiguri",
    "JNV Malda",
    "JNV Murshidabad",
    "JNV Nadia",
    "JNV North 24 Parganas",
    "JNV Paschim Medinipur",
    "JNV Purba Bardhaman",
    "JNV Purulia",
    "JNV South 24 Parganas",
    "JNV Uttar Dinajpur",
  ],
};
