// import { type Job } from "~/types/job.type";
// Work Modes
export const workModes = ["In Office", "Hybrid", "Remote"];

// Job Sectors
export const jobSectors = [
  "Government",
  "Private",
  "Non-profit Organisation",
  "Volunteer",
];

// export const jobs: Job[] = [
//   {
//     title: "Software Engineer",
//     company: "Microsoft",
//     description: "Develop software for Microsoft products",
//     postedBy: "John Doe",
//     socialLinks: [
//       "https://www.linkedin.com/in/jane-smith/",
//       "https://twitter.com/janesmith",
//     ],
//     link: "https://www.microsoft.com/careers",
//     salaryRange: "$100,000 - $150,000",
//     experienceRequired: "3+ years",
//     location: "Redmond, WA",
//     type: "Private",
//     sector: "IT",
//   },
//   {
//     title: "Marketing Manager",
//     company: "Amazon",
//     description: "Manage marketing campaigns for Amazon products",
//     postedBy: "Jane Smith",
//     socialLinks: [
//       "https://www.linkedin.com/in/jane-smith/",
//       "https://twitter.com/janesmith",
//     ],
//     link: "https://www.amazon.com/careers",
//     salaryRange: "$80,000 - $120,000",
//     experienceRequired: "5+ years",
//     location: "Seattle, WA",
//     type: "Private",
//     sector: "Marketing",
//   },
//   {
//     title: "Accountant",
//     company: "Deloitte",
//     description: "Provide accounting services to clients",
//     postedBy: "Bob Johnson",
//     socialLinks: [
//       "https://www.linkedin.com/in/jane-smith/",
//       "https://twitter.com/janesmith",
//     ],
//     link: "https://www.deloitte.com/careers",
//     salaryRange: "$60,000 - $80,000",
//     experienceRequired: "2+ years",
//     location: "New York, NY",
//     type: "Private",
//     sector: "Accounting",
//   },
//   {
//     title: "Software Developer",
//     company: "ABC Technologies",
//     description: "We are looking for a software developer to join our team.",
//     postedBy: "John Doe",
//     socialLinks: ["https://www.linkedin.com/in/john-doe/"],
//     link: "https://www.example.com/software-developer",
//     salaryRange: "INR 5,00,000 - INR 10,00,000",
//     experienceRequired: "3-5 years",
//     location: "Indore, Madhya Pradesh",
//     type: "Private",
//     sector: "IT",
//   },
//   {
//     title: "Marketing Manager",
//     company: "XYZ Corporation",
//     description:
//       "We are looking for a marketing manager to lead our marketing team.",
//     postedBy: "Jane Smith",
//     socialLinks: [
//       "https://www.linkedin.com/in/jane-smith/",
//       "https://twitter.com/janesmith",
//     ],
//     link: "https://www.example.com/marketing-manager",
//     salaryRange: "INR 8,00,000 - INR 12,00,000",
//     experienceRequired: "5-7 years",
//     location: "Mumbai, Maharashtra",
//     type: "Private",
//     sector: "Marketing",
//   },
//   {
//     title: "HR Manager",
//     company: "PQR Inc.",
//     description: "We are looking for an HR manager to join our team.",
//     postedBy: "Bob Johnson",
//     socialLinks: ["https://www.linkedin.com/in/bob-johnson/"],
//     link: "https://www.example.com/hr-manager",
//     salaryRange: "INR 6,00,000 - INR 9,00,000",
//     experienceRequired: "2-4 years",
//     location: "Bengaluru, Karnataka",
//     type: "Private",
//     sector: "HR",
//   },
//   {
//     title: "Accountant",
//     company: "LMN Inc.",
//     description: "We are looking for an accountant to join our team.",
//     postedBy: "Alice Brown",
//     socialLinks: ["https://www.linkedin.com/in/alice-brown/"],
//     link: "https://www.example.com/accountant",
//     salaryRange: "INR 4,00,000 - INR 7,00,000",
//     experienceRequired: "1-3 years",
//     location: "Chennai, Tamil Nadu",
//     type: "Private",
//     sector: "Accounting",
//   },
//   {
//     title: "Sales Executive",
//     company: "EFG Corporation",
//     description: "We are looking for a sales executive to join our team.",
//     postedBy: "Tom Wilson",
//     socialLinks: ["https://www.linkedin.com/in/tom-wilson/"],
//     link: "https://www.example.com/sales-executive",
//     salaryRange: "INR 3,00,000 - INR 5,00,000",
//     experienceRequired: "0-1 years",
//     location: "Hyderabad, Telangana",
//     type: "Private",
//     sector: "Sales",
//   },
//   {
//     title: "Software Engineer",
//     company: "Microsoft",
//     description: "Develop software for Microsoft products",
//     postedBy: "John Doe",
//     socialLinks: [
//       "https://www.linkedin.com/in/jane-smith/",
//       "https://twitter.com/janesmith",
//     ],
//     link: "https://www.microsoft.com/careers",
//     salaryRange: "$100,000 - $150,000",
//     experienceRequired: "3+ years",
//     location: "Redmond, WA",
//     type: "Private",
//     sector: "IT",
//   },
//   {
//     title: "Marketing Manager",
//     company: "Amazon",
//     description: "Manage marketing campaigns for Amazon products",
//     postedBy: "Jane Smith",
//     socialLinks: [
//       "https://www.linkedin.com/in/jane-smith/",
//       "https://twitter.com/janesmith",
//     ],
//     link: "https://www.amazon.com/careers",
//     salaryRange: "$80,000 - $120,000",
//     experienceRequired: "5+ years",
//     location: "Seattle, WA",
//     type: "Private",
//     sector: "Marketing",
//   },
//   {
//     title: "Accountant",
//     company: "Deloitte",
//     description: "Provide accounting services to clients",
//     postedBy: "Bob Johnson",
//     socialLinks: [
//       "https://www.linkedin.com/in/jane-smith/",
//       "https://twitter.com/janesmith",
//     ],
//     link: "https://www.deloitte.com/careers",
//     salaryRange: "$60,000 - $80,000",
//     experienceRequired: "2+ years",
//     location: "New York, NY",
//     type: "Private",
//     sector: "Accounting",
//   },
//   {
//     title: "Software Developer",
//     company: "ABC Technologies",
//     description: "We are looking for a software developer to join our team.",
//     postedBy: "John Doe",
//     socialLinks: ["https://www.linkedin.com/in/john-doe/"],
//     link: "https://www.example.com/software-developer",
//     salaryRange: "INR 5,00,000 - INR 10,00,000",
//     experienceRequired: "3-5 years",
//     location: "Indore, Madhya Pradesh",
//     type: "Private",
//     sector: "IT",
//   },
//   {
//     title: "Marketing Manager",
//     company: "XYZ Corporation",
//     description:
//       "We are looking for a marketing manager to lead our marketing team.",
//     postedBy: "Jane Smith",
//     socialLinks: [
//       "https://www.linkedin.com/in/jane-smith/",
//       "https://twitter.com/janesmith",
//     ],
//     link: "https://www.example.com/marketing-manager",
//     salaryRange: "INR 8,00,000 - INR 12,00,000",
//     experienceRequired: "5-7 years",
//     location: "Mumbai, Maharashtra",
//     type: "Private",
//     sector: "Marketing",
//   },
//   {
//     title: "HR Manager",
//     company: "PQR Inc.",
//     description: "We are looking for an HR manager to join our team.",
//     postedBy: "Bob Johnson",
//     socialLinks: ["https://www.linkedin.com/in/bob-johnson/"],
//     link: "https://www.example.com/hr-manager",
//     salaryRange: "INR 6,00,000 - INR 9,00,000",
//     experienceRequired: "2-4 years",
//     location: "Bengaluru, Karnataka",
//     type: "Private",
//     sector: "HR",
//   },
//   {
//     title: "Accountant",
//     company: "LMN Inc.",
//     description: "We are looking for an accountant to join our team.",
//     postedBy: "Alice Brown",
//     socialLinks: ["https://www.linkedin.com/in/alice-brown/"],
//     link: "https://www.example.com/accountant",
//     salaryRange: "INR 4,00,000 - INR 7,00,000",
//     experienceRequired: "1-3 years",
//     location: "Chennai, Tamil Nadu",
//     type: "Private",
//     sector: "Accounting",
//   },
//   {
//     title: "Sales Executive",
//     company: "EFG Corporation",
//     description: "We are looking for a sales executive to join our team.",
//     postedBy: "Tom Wilson",
//     socialLinks: ["https://www.linkedin.com/in/tom-wilson/"],
//     link: "https://www.example.com/sales-executive",
//     salaryRange: "INR 3,00,000 - INR 5,00,000",
//     experienceRequired: "0-1 years",
//     location: "Hyderabad, Telangana",
//     type: "Private",
//     sector: "Sales",
//   },
// ];
